import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import marshallIcon from "../../public/img/marshall-icon-black.svg"
import marshallogo from "../../public/img/marshall-logo.png"
import original from "../../public/img/marshall-original-home.png"
import { api } from "~/utils/api";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex space-x-0 bg-red-600 align-middle justify-center px-4">
        <div className="max-w-2xl py-2 w-full flex justify-between space-x-3">
        <Image
          alt="Marshall icon"
          src={marshallIcon}
          className="w-4 h-auto"
        />
        <ul className="flex justify-center align-middle space-x-3">
          <li className="self-center">Carrinho</li>
          <li className="self-center">
          <button
            className="rounded-full px-7 py-3 bg-white/10 font-semibold text-white no-underline transition hover:bg-white/20"
            onClick={sessionData ? () => void signOut() : () => void signIn()}
          >
            {sessionData ? "Sign out" : "Sign in"}
          </button>
          </li>
        </ul>
        </div>
      </nav>
      <main className="flex min-h-screen flex-col items-center bg-neutral-900">
        <div className="max-w-sm">
      <Image
          alt="Marshall logo"
          src={marshallogo}
          className="max-w-5"
        />
        </div>
        <div className="flex flex-col max-w-sm space-y-5 p-3">
          <h2 className="bg-neutral-950 text-red-600 font-bold text-2xl p-2">Marshall Original - 250ml</h2>
          <Image src={original} alt="Marshall Original" />
          <div className="flex flex-col space-y-2">
          <p className="text-red-600 font-bold text-lg">Picância: 🔥🔥 • • •</p>
          <p className="text-red-600 font-bold text-lg">R$25,00</p>
          <p className="text-neutral-50">A Marshall é um molho de pimenta artesanal fermentado com especiarias no estilo sriracha e de picância baixa ou mediana (isso é completamente subjetivo, se você já comeu e achou ela “fraquinha” parabéns para você e o seu butãozinho de diamante).</p>
          </div>
          <div className="flex space-x-3">
          <input type="number" name="qnty" id="qntyOriginal" className="outline-none focus:outline-none text-center w-20 border border-red-600 rounded bg-transparent font-semibold text-md text-gray-50 "/>
          <button
            className="rounded-full px-7 py-3 bg-white/10 font-semibold text-white no-underline transition hover:bg-white/20"
          >Adicionar ao carrinho</button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
