import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import marshallIcon from "../../public/img/marshall-icon-black.svg";
import marshallogo from "../../public/img/marshall-logo.png";
import original from "../../public/img/marshall-original-home.png";
import { api } from "~/utils/api";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-center space-x-0 bg-red-600 px-4 align-middle">
        <div className="flex w-full max-w-2xl justify-between space-x-3 py-2">
          <Image
            alt="Marshall icon"
            src={marshallIcon}
            className="h-auto w-4"
          />
          <ul className="flex justify-center space-x-3 align-middle">
            <li className="self-center">Carrinho</li>
            <li className="self-center">
              <button
                className="rounded-full bg-white/10 px-7 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={
                  sessionData ? () => void signOut() : () => void signIn()
                }
              >
                {sessionData ? "Sign out" : "Sign in"}
              </button>
            </li>
          </ul>
        </div>
      </nav>
      <main className="flex min-h-screen flex-col items-center bg-neutral-900 pb-14 relative">
        <div className="max-w-sm">
          <Image alt="Marshall logo" src={marshallogo} className="max-w-5" />
        </div>
        <div className="flex max-w-2xl flex-wrap justify-center gap-8">
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
        </div>
        <button className="absolute -bottom-6 rounded-xl border-2 border-red-600 px-7 py-3 font-semibold text-neutral-50 no-underline transition bg-neutral-900 hover:bg-red-600 hover:text-neutral-950">
          Veja nossas bobagens no Instagram
        </button>
        
      </main>
      <section className="w-full bg-neutral-950 pt-12 py-5">
          <h2 className="mb-4 text-center text-2xl font-bold uppercase text-red-600">
            Onde encontrar a Pimenta Marshall
          </h2>
          <div className="mx-auto flex max-w-xs space-x-3 rounded-xl border-2 border-red-600 p-3">
            <div className="flex flex-col space-y-2">
              <h4 className="text-lg font-bold text-red-600">
                MERCADO CENTRAL - Paraíso das Pimentas
              </h4>
              <p className="text-amber-500">Loja</p>
              <p className="text-neutral-50">
                Av. Augusto de Lima, 744 - Centro - Belo Horizonte
              </p>
              <p className="text-neutral-50">
                Instagram:{" "}
                <a
                  href="https://www.instagram.com/paraisodaspimentas/"
                  className="text-red-600"
                >
                  @paraisodaspimentas
                </a>
              </p>
            </div>
          </div>
        </section>
        <footer className="w-full text-center bg-black text-neutral-700 text-xs py-3">
          Copyright &copy; {new Date().getFullYear()} Pimenta Marshall
        </footer>
    </>
  );
};

export default Home;

const ProductCard: React.FC = () => {
  return (
    <div className="flex max-w-xs flex-col space-y-5 p-3">
      <h2 className="bg-neutral-950 p-2 text-2xl font-bold text-red-600">
        Marshall Original - 250ml
      </h2>
      <Image src={original} alt="Marshall Original" className=""/>
      <div className="flex flex-col space-y-2">
        <p className="text-lg font-bold text-red-600">Picância: 🔥🔥 • • •</p>
        <p className="text-lg font-bold text-red-600">R$25,00</p>
        <p className="text-neutral-50">
          A Marshall é um molho de pimenta artesanal fermentado com especiarias
          no estilo sriracha e de picância baixa ou mediana (isso é
          completamente subjetivo, se você já comeu e achou ela “fraquinha”
          parabéns para você e o seu butãozinho de diamante).
        </p>
      </div>
      <div className="flex space-x-3">
        <input
          type="number"
          name="qnty"
          id="qntyOriginal"
          className="text-md w-20 rounded border border-red-600 bg-transparent text-center font-semibold text-gray-50 outline-none focus:outline-none "
        />
        <button className="rounded-full bg-white/10 px-7 py-3 font-semibold text-white no-underline transition hover:bg-white/20">
          Adicionar ao carrinho
        </button>
      </div>
    </div>
  );
};

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
